### ISSUE TITLE
Issue 3: Add Feature for Category Filtering in Transaction History

### ISSUE THREAD

**Issue by vaibhavkothari33** [vaibhavkothari33/PaiseKaHisab#3]
Description:
We want to improve the transaction history table by adding a category filtering feature. This will allow users to filter their expenses based on specific categories (e.g., Food, Shopping, Rent, etc.).

Task:
Add a dropdown or buttons for category selection on the transaction history page.
When a category is selected, only the transactions related to that category should be displayed.
Implement this feature without refreshing the page (using JavaScript).

Skills Required:
JavaScript
HTML/CSS

Level:
Intermediate

**Comment by Jatinsinha03** [comment]
Done with this issue, assign this also to me
<img width="1439" alt="Screenshot 2024-10-10 at 1 56 21 AM" src="https://github.com/user-attachments/assets/c69d6d70-ea9d-4a8e-a03f-61c7fa4a6c4e">
