### ISSUE TITLE
Issue 4:  Replace Default Alert Box with Custom Alert Box for Input Validation

### ISSUE THREAD

**Issue by vaibhavkothari33** [vaibhavkothari33/PaiseKaHisab#4]
#### **Description:**
Currently, when the user does not input a value in fields like **name** or **price**, the default browser alert box is displayed. We want to improve the user experience by replacing this with a custom alert box that displays more user-friendly messages.

#### **Tasks:**
1. Create a custom alert box that will replace the default alert.
2. The alert box should display the appropriate error message (e.g., "Please enter a name" or "Price is required").
3. Add a close button to the custom alert box that allows the user to dismiss the alert.
4. Style the alert box to match the rest of the website’s theme (e.g., a clean, modern look with Tailwind CSS or any existing styles).
5. Ensure the alert box is responsive and works well on both desktop and mobile.

#### **Additional Details:**
- The custom alert box should be hidden by default and only shown when an error occurs.
- It should not use the default `alert()` function but instead manipulate the DOM to display the error message.
- The alert box should overlay the content of the page in the center and have a semi-transparent background to make it more prominent.

#### **Acceptance Criteria:**
- The custom alert box is shown when validation errors occur (e.g., missing name or price).
- The custom alert box is hidden after the user clicks the close button.
- The box is visually appealing and fits the website’s design.
- Works seamlessly across mobile and desktop devices.

**Comment by TrueCoderSja** [comment]
I am working on the issue. I will create a JS warning function which can be imported into any page by `<script>` tags and can be used anywhere. So, please assign the issue to me.

Regards, 
Peeyush Kumar Gautam

**Comment by vaibhavkothari33** [comment]
the alert box is added to only expence page and it need to be added in loan/lend section also

**Comment by TrueCoderSja** [comment]
Working on it....

**Comment by Jatinsinha03** [comment]
Is the issue solved ? If not assign it to me.
